# Generated by Django 3.1.6 on 2021-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録時間')),
                ('country', models.TextField(max_length=100, verbose_name='国')),
                ('interest_rate', models.FloatField(blank=True, verbose_name='利子率')),
            ],
            options={
                'verbose_name': '採取データ',
                'verbose_name_plural': '採取データ',
            },
        ),
    ]
