# Generated by Django 3.1.6 on 2021-02-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='year')),
                ('country', models.TextField(max_length=100, verbose_name='country')),
                ('interest_rate', models.FloatField(blank=True, verbose_name='interest_rate')),
            ],
            options={
                'db_table': 'interest_rate',
            },
        ),
    ]
