# Generated by Django 3.1.6 on 2021-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210211_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.TextField(max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.CharField(max_length=255, verbose_name='year'),
        ),
    ]
