# Generated by Django 3.1.6 on 2021-02-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210211_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.CharField(max_length=20, verbose_name='year'),
        ),
    ]
